name: Sanity self-tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  provisioner-testing-farm:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-26.04
    environment:
      name: testing-farm
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install -y python3-pytest python3-pytest-xdist
      - run: python3 -m pip install .
      - name: Run tests
        run: |
          python3 -m pytest -svvx -n 50 tests/provisioner/test_testingfarm.py
        env:
          TESTING_FARM_COMPOSE: CentOS-Stream-10
          TESTING_FARM_API_TOKEN: ${{ secrets.TESTING_FARM_API_TOKEN }}

  provisioner-podman:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install -y python3-pytest podman
      - run: python3 -m pip install .
      - name: Run tests
        run: |
          python3 -m pytest -svvx tests/provisioner/test_podman*.py

  provisioners-small:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install -y python3-pytest rsync
      - run: python3 -m pip install .
      - name: Run tests
        run: |
          python3 -m pytest -svvx \
              tests/provisioner \
              --ignore-glob=tests/provisioner/test_{podman*,testingfarm,tempvirt}.py

  connection:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install -y python3-pytest podman openssh-client
      - run: python3 -m pip install .
      - name: Run tests
        run: |
          python3 -m pytest -svvx tests/connection

  executors:
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        image: [fedora, centos10, centos9, centos8, centos7]
        backend: [podman, ssh]
        exclude:
          - image: centos7
            backend: ssh
          - image: centos8
            backend: ssh
    name: executors-${{ matrix.image }}-${{ matrix.backend }}
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install -y python3-pytest podman openssh-client rsync
      - run: python3 -m pip install .
      - name: Run tests
        run: >-
          python3 -m pytest -svvx
          -k "${{ matrix.image }}-${{ matrix.backend }}"
          tests/executor

  executors-small:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install -y python3-pytest
      - run: python3 -m pip install .
      - name: Run tests
        run: |
          python3 -m pytest -svvx \
              tests/executor/command \
              tests/executor/fmf/test_discover.py \
              tests/executor/fmf/test_metadata.py

  aggregators:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install -y python3-pytest
      - run: python3 -m pip install .
      - name: Run tests
        run: |
          python3 -m pytest -svvx tests/aggregator

  orchestrators:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt-get install -y python3-pytest
      - run: python3 -m pip install .
      - name: Run tests
        run: |
          python3 -m pytest -svvx tests/orchestrator
